In [1]:
import pandas as pd

In [2]:
df_train = pd.read_csv("data/train.csv")

In [10]:
display(df_train)

,id,is_appartment,area,added_time,bedrooms,new_building,postcode,lat,lon,advertiser,foto_amount,is_promoted,subtype,sticker,price_drop_date,energy_value,energy_label,province,price
0,tr0,True,88.0,141725167,2.0,0,8300,51.342160,3.287791,Vastio,12.0,1,Appartement,NaN,NaN,210.0,c,West-Vlaanderen,599000.00
1,tr1,True,55.0,132223171,1.0,0,1800,50.933980,4.436390,Ring Consult,10.0,1,Appartement,NaN,NaN,92.0,a,Vlaams-Brabant,199000.00
2,tr2,False,333.0,119151262,4.0,0,3294,50.996456,5.045376,Hillewaere Heist-op-den-Berg,30.0,1,Villa,NaN,2024-06-08 23:29:39,NaN,f,Vlaams-Brabant,875000.00
3,tr3,False,517.0,137313038,5.0,0,1700,50.843364,4.274004,Living Stone Dilbeek,31.0,1,Eengezinswoning,NaN,NaN,322.0,d,Vlaams-Brabant,649000.00
4,tr4,True,99.0,137303955,3.0,0,8300,51.348180,3.276942,Colpin Heist,13.0,1,Appartement,NaN,NaN,161.0,b,West-Vlaanderen,765000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27066,tr27066,True,81.0,141439187,2.0,0,9140,51.129260,4.217450,Uw-Huis Bv,8.0,1,Appartement,NaN,NaN,248.0,c,Oost-Vlaanderen,159500.00
27067,tr27067,False,165.0,141979060,3.0,0,1701,50.817861,4.244707,We Invest Dilbeek,14.0,1,Woning,NaN,NaN,NaN,e,Vlaams-Brabant,375000.00
27068,tr27068,False,157.0,142750425,4.0,0,8600,51.025310,2.866690,Residentie Vastgoed,19.0,1,Woning,new,NaN,299.0,c,West-Vlaanderen,249000.00
27069,tr27069,True,113.0,141440600,2.0,1,3920,51.225782,5.313655,Idealis Vastgoed,6.0,1,Appartement,NaN,NaN,NaN,NaN,Limburg,333855.56
27070,tr27070,True,39.0,121328619,1.0,0,1160,50.816558,4.425947,ClintImmo,8.0,1,Serviceflat,NaN,NaN,268.0,e,Hoofdstedelijk Gewest Brussel,135000.00